// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: masterworker.proto
#ifndef GRPC_masterworker_2eproto__INCLUDED
#define GRPC_masterworker_2eproto__INCLUDED

#include "masterworker.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace masterworker {

class WorkerImpl final {
 public:
  static constexpr char const* service_full_name() {
    return "masterworker.WorkerImpl";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Map(::grpc::ClientContext* context, const ::masterworker::Shard& request, ::masterworker::MapReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::MapReply>> AsyncMap(::grpc::ClientContext* context, const ::masterworker::Shard& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::MapReply>>(AsyncMapRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::MapReply>> PrepareAsyncMap(::grpc::ClientContext* context, const ::masterworker::Shard& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::MapReply>>(PrepareAsyncMapRaw(context, request, cq));
    }
    virtual ::grpc::Status Reduce(::grpc::ClientContext* context, const ::masterworker::ReduceFile& request, ::masterworker::ReduceReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::ReduceReply>> AsyncReduce(::grpc::ClientContext* context, const ::masterworker::ReduceFile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::ReduceReply>>(AsyncReduceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::ReduceReply>> PrepareAsyncReduce(::grpc::ClientContext* context, const ::masterworker::ReduceFile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::ReduceReply>>(PrepareAsyncReduceRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Map(::grpc::ClientContext* context, const ::masterworker::Shard* request, ::masterworker::MapReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Map(::grpc::ClientContext* context, const ::masterworker::Shard* request, ::masterworker::MapReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Map(::grpc::ClientContext* context, const ::masterworker::Shard* request, ::masterworker::MapReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void Reduce(::grpc::ClientContext* context, const ::masterworker::ReduceFile* request, ::masterworker::ReduceReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Reduce(::grpc::ClientContext* context, const ::masterworker::ReduceFile* request, ::masterworker::ReduceReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Reduce(::grpc::ClientContext* context, const ::masterworker::ReduceFile* request, ::masterworker::ReduceReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::MapReply>* AsyncMapRaw(::grpc::ClientContext* context, const ::masterworker::Shard& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::MapReply>* PrepareAsyncMapRaw(::grpc::ClientContext* context, const ::masterworker::Shard& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::ReduceReply>* AsyncReduceRaw(::grpc::ClientContext* context, const ::masterworker::ReduceFile& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::ReduceReply>* PrepareAsyncReduceRaw(::grpc::ClientContext* context, const ::masterworker::ReduceFile& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Map(::grpc::ClientContext* context, const ::masterworker::Shard& request, ::masterworker::MapReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::MapReply>> AsyncMap(::grpc::ClientContext* context, const ::masterworker::Shard& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::MapReply>>(AsyncMapRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::MapReply>> PrepareAsyncMap(::grpc::ClientContext* context, const ::masterworker::Shard& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::MapReply>>(PrepareAsyncMapRaw(context, request, cq));
    }
    ::grpc::Status Reduce(::grpc::ClientContext* context, const ::masterworker::ReduceFile& request, ::masterworker::ReduceReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::ReduceReply>> AsyncReduce(::grpc::ClientContext* context, const ::masterworker::ReduceFile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::ReduceReply>>(AsyncReduceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::ReduceReply>> PrepareAsyncReduce(::grpc::ClientContext* context, const ::masterworker::ReduceFile& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::ReduceReply>>(PrepareAsyncReduceRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Map(::grpc::ClientContext* context, const ::masterworker::Shard* request, ::masterworker::MapReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Map(::grpc::ClientContext* context, const ::masterworker::Shard* request, ::masterworker::MapReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Map(::grpc::ClientContext* context, const ::masterworker::Shard* request, ::masterworker::MapReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void Reduce(::grpc::ClientContext* context, const ::masterworker::ReduceFile* request, ::masterworker::ReduceReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Reduce(::grpc::ClientContext* context, const ::masterworker::ReduceFile* request, ::masterworker::ReduceReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Reduce(::grpc::ClientContext* context, const ::masterworker::ReduceFile* request, ::masterworker::ReduceReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::masterworker::MapReply>* AsyncMapRaw(::grpc::ClientContext* context, const ::masterworker::Shard& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::masterworker::MapReply>* PrepareAsyncMapRaw(::grpc::ClientContext* context, const ::masterworker::Shard& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::masterworker::ReduceReply>* AsyncReduceRaw(::grpc::ClientContext* context, const ::masterworker::ReduceFile& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::masterworker::ReduceReply>* PrepareAsyncReduceRaw(::grpc::ClientContext* context, const ::masterworker::ReduceFile& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Map_;
    const ::grpc::internal::RpcMethod rpcmethod_Reduce_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Map(::grpc::ServerContext* context, const ::masterworker::Shard* request, ::masterworker::MapReply* response);
    virtual ::grpc::Status Reduce(::grpc::ServerContext* context, const ::masterworker::ReduceFile* request, ::masterworker::ReduceReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Map : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Map() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Map() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Map(::grpc::ServerContext* /*context*/, const ::masterworker::Shard* /*request*/, ::masterworker::MapReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMap(::grpc::ServerContext* context, ::masterworker::Shard* request, ::grpc::ServerAsyncResponseWriter< ::masterworker::MapReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Reduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Reduce() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Reduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reduce(::grpc::ServerContext* /*context*/, const ::masterworker::ReduceFile* /*request*/, ::masterworker::ReduceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReduce(::grpc::ServerContext* context, ::masterworker::ReduceFile* request, ::grpc::ServerAsyncResponseWriter< ::masterworker::ReduceReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Map<WithAsyncMethod_Reduce<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Map : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Map() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::masterworker::Shard, ::masterworker::MapReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::masterworker::Shard* request, ::masterworker::MapReply* response) { return this->Map(context, request, response); }));}
    void SetMessageAllocatorFor_Map(
        ::grpc::experimental::MessageAllocator< ::masterworker::Shard, ::masterworker::MapReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::masterworker::Shard, ::masterworker::MapReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Map() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Map(::grpc::ServerContext* /*context*/, const ::masterworker::Shard* /*request*/, ::masterworker::MapReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Map(
      ::grpc::CallbackServerContext* /*context*/, const ::masterworker::Shard* /*request*/, ::masterworker::MapReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Map(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::masterworker::Shard* /*request*/, ::masterworker::MapReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Reduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Reduce() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::masterworker::ReduceFile, ::masterworker::ReduceReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::masterworker::ReduceFile* request, ::masterworker::ReduceReply* response) { return this->Reduce(context, request, response); }));}
    void SetMessageAllocatorFor_Reduce(
        ::grpc::experimental::MessageAllocator< ::masterworker::ReduceFile, ::masterworker::ReduceReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::masterworker::ReduceFile, ::masterworker::ReduceReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Reduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reduce(::grpc::ServerContext* /*context*/, const ::masterworker::ReduceFile* /*request*/, ::masterworker::ReduceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Reduce(
      ::grpc::CallbackServerContext* /*context*/, const ::masterworker::ReduceFile* /*request*/, ::masterworker::ReduceReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Reduce(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::masterworker::ReduceFile* /*request*/, ::masterworker::ReduceReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Map<ExperimentalWithCallbackMethod_Reduce<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Map<ExperimentalWithCallbackMethod_Reduce<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Map : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Map() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Map() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Map(::grpc::ServerContext* /*context*/, const ::masterworker::Shard* /*request*/, ::masterworker::MapReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Reduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Reduce() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Reduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reduce(::grpc::ServerContext* /*context*/, const ::masterworker::ReduceFile* /*request*/, ::masterworker::ReduceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Map : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Map() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Map() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Map(::grpc::ServerContext* /*context*/, const ::masterworker::Shard* /*request*/, ::masterworker::MapReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMap(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Reduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Reduce() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Reduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reduce(::grpc::ServerContext* /*context*/, const ::masterworker::ReduceFile* /*request*/, ::masterworker::ReduceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReduce(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Map : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Map() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Map(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Map() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Map(::grpc::ServerContext* /*context*/, const ::masterworker::Shard* /*request*/, ::masterworker::MapReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Map(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Map(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Reduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Reduce() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Reduce(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Reduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reduce(::grpc::ServerContext* /*context*/, const ::masterworker::ReduceFile* /*request*/, ::masterworker::ReduceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Reduce(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Reduce(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Map : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Map() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::masterworker::Shard, ::masterworker::MapReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::masterworker::Shard, ::masterworker::MapReply>* streamer) {
                       return this->StreamedMap(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Map() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Map(::grpc::ServerContext* /*context*/, const ::masterworker::Shard* /*request*/, ::masterworker::MapReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMap(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::masterworker::Shard,::masterworker::MapReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Reduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Reduce() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::masterworker::ReduceFile, ::masterworker::ReduceReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::masterworker::ReduceFile, ::masterworker::ReduceReply>* streamer) {
                       return this->StreamedReduce(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Reduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Reduce(::grpc::ServerContext* /*context*/, const ::masterworker::ReduceFile* /*request*/, ::masterworker::ReduceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReduce(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::masterworker::ReduceFile,::masterworker::ReduceReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Map<WithStreamedUnaryMethod_Reduce<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Map<WithStreamedUnaryMethod_Reduce<Service > > StreamedService;
};

}  // namespace masterworker


#endif  // GRPC_masterworker_2eproto__INCLUDED
